language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
  - cd data && sh download_data.sh && cd ..
script: 
  - coverage erase
  - coverage run -m pytest
  - find . -name '*.py' -exec coverage report -m {} \;