language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
  - pushd mnist-tf/app/data 1>/dev/null && sh download_data.sh && popd 1>/dev/null
script: 
  - coverage erase
  - coverage run -m pytest
  - find . -name '*.py' -exec coverage report -m {} \;